baseURL = 'https://fuzi.gyulai.cloud/'
languageCode = 'hu-hu'
title = 'Füzi-Gyulai'
theme = 'devise'
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; Copyright 2025, Daniel Gyulai"

# Configuration Features
[params]
  # description = "Your meta description"      # Your meta description of the site
  header_title = "Luca & Dániel"                 # Your header title
  header_subtitle = " " # Your header subtitle
  # home_image = "/images/avatar.png"          # Path to header image starting from the static directory (optional)
  recent_posts = 0                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    # backgroundColor = "#f8f9fa"
    backgroundColor = "#fff2ff"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"        # First-choice font
    # fontColor = "#212529"
    fontColor = "#252125"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
